function main() ~> Nothing {
    bsm {
        copy sp, r100
    }
    let a: mutable U32 = 42;
    let b: mutable U32 = 27;
    bsm {
        assert sp, r100
    }
    a = b;
    bsm {
        assert sp, r100
    }
    std::assert_equals(a, b);
    a = b = 5;
    bsm {
        assert sp, r100
    }
    std::assert_equals(a, 5);
    std::assert_equals(b, 5);
    bsm {
        assert sp, r100
    }
    a = 12;
    std::assert(a != b);
    std::assert_equals(a, 12);
    a = a;
    std::assert_equals(a, 12);
    std::assert(a != b);
}
